'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type Product={id:string;slug:string;name:string;maker:string;category:string;description:string;story:string;image:string;price:number;stock:number;featured:number};
type CartLine={product:Product;quantity:number};
type View='shop'|'story'|'makers';

const fallback:Product[]=[
  {id:'chair-solihiya',slug:'solihiya-lounge-chair',name:'Solihiya Lounge Chair',maker:'Casa Marikit',category:'Home',description:'A low lounge chair hand-caned in traditional solihiya weave, with a solid Philippine mahogany frame.',story:'Built in Pampanga by a third-generation furniture workshop.',image:'https://images.unsplash.com/photo-1598300056393-4aac492f4344?auto=format&fit=crop&w=1000&q=85',price:1280000,stock:8,featured:1},
  {id:'tote-habi',slug:'handwoven-market-tote',name:'Handwoven Market Tote',maker:'Habi Studio',category:'Accessories',description:'An everyday carryall woven from abacá and finished with vegetable-tanned leather handles.',story:'Woven over three days by a small women-led cooperative in Bicol.',image:'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=1000&q=85',price:245000,stock:22,featured:1},
  {id:'stoneware-taal',slug:'taal-stoneware-set',name:'Taal Stoneware Set',maker:'Likhang Lupa',category:'Tableware',description:'Four softly speckled stoneware pieces, wheel-thrown and glazed by hand.',story:'Each piece is fired in small batches in a Batangas hillside studio.',image:'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1000&q=85',price:390000,stock:16,featured:1},
  {id:'lamp-capiz',slug:'capiz-glow-lamp',name:'Capiz Glow Lamp',maker:'Isla Lightworks',category:'Home',description:'A warm table light built from hand-cut capiz shell and brushed brass.',story:'Assembled by artisan metalworkers and shell cutters in Cebu.',image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=85',price:565000,stock:11,featured:0},
  {id:'throw-inabel',slug:'inabel-grid-throw',name:'Inabel Grid Throw',maker:'Amianan Loom',category:'Textiles',description:'A graphic cotton throw woven on traditional upright looms.',story:'The pattern is a modern study of classic Ilocano binakul geometry.',image:'https://images.unsplash.com/photo-1583845112203-454c2254edb3?auto=format&fit=crop&w=1000&q=85',price:320000,stock:18,featured:0},
  {id:'tray-narra',slug:'narra-serving-tray',name:'Narra Serving Tray',maker:'Ukit Works',category:'Tableware',description:'A sculptural serving tray shaped from responsibly reclaimed narra.',story:'Carved and finished by hand in a Laguna family workshop.',image:'https://images.unsplash.com/photo-1531988042231-d39a9cc12a9a?auto=format&fit=crop&w=1000&q=85',price:285000,stock:14,featured:0},
  {id:'vase-terracotta',slug:'terracotta-stem-vase',name:'Terracotta Stem Vase',maker:'Likhang Lupa',category:'Home',description:'A tall, tactile vessel for a single dramatic branch or gathered stems.',story:'Hand-coiled with locally sourced clay and fired to a sun-warmed tone.',image:'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1000&q=85',price:175000,stock:20,featured:0},
  {id:'pouch-pandan',slug:'pandan-weekend-pouch',name:'Pandan Weekend Pouch',maker:'Habi Studio',category:'Accessories',description:'A softly structured woven pouch with cotton lining and brass zip.',story:'Natural pandan leaves are prepared, dyed, and woven entirely by hand.',image:'https://images.unsplash.com/photo-1559563458-527698bf5295?auto=format&fit=crop&w=1000&q=85',price:128000,stock:25,featured:0},
];
const peso=(cents:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(cents/100);

export default function Storefront(){
  const [products,setProducts]=useState<Product[]>(fallback),[view,setView]=useState<View>('shop'),[category,setCategory]=useState('All'),[sort,setSort]=useState('featured'),[query,setQuery]=useState(''),[searching,setSearching]=useState(false),[cart,setCart]=useState<CartLine[]>([]),[cartOpen,setCartOpen]=useState(false),[selected,setSelected]=useState<Product|null>(null),[favorites,setFavorites]=useState<Set<string>>(new Set()),[checkout,setCheckout]=useState(false),[submitting,setSubmitting]=useState(false),[error,setError]=useState(''),[orderId,setOrderId]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>{fetch('/api/products').then(r=>r.ok?r.json():Promise.reject()).then(d=>setProducts(d.products)).catch(()=>{});const saved=localStorage.getItem('kumbini-cart');if(saved)try{setCart(JSON.parse(saved))}catch{}},[]);
  useEffect(()=>{localStorage.setItem('kumbini-cart',JSON.stringify(cart))},[cart]);
  const categories=['All',...Array.from(new Set(products.map(p=>p.category)))];
  const shown=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&(`${p.name} ${p.maker} ${p.category}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:b.featured-a.featured),[products,category,query,sort]);
  const count=cart.reduce((s,l)=>s+l.quantity,0),subtotal=cart.reduce((s,l)=>s+l.product.price*l.quantity,0),shipping=subtotal>=500000?0:18000;
  const add=(product:Product)=>{setCart(c=>{const line=c.find(l=>l.product.id===product.id);return line?c.map(l=>l.product.id===product.id?{...l,quantity:Math.min(l.quantity+1,product.stock)}:l):[...c,{product,quantity:1}]});setSelected(null);setCartOpen(true)};
  const quantity=(id:string,next:number)=>setCart(c=>next<1?c.filter(l=>l.product.id!==id):c.map(l=>l.product.id===id?{...l,quantity:next}:l));
  const toggleFavorite=(id:string)=>setFavorites(f=>{const n=new Set(f);n.has(id)?n.delete(id):n.add(id);return n});
  const submitOrder=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSubmitting(true);setError('');const fd=new FormData(e.currentTarget);const customer=Object.fromEntries(['name','email','phone','address','city','postalCode'].map(k=>[k,fd.get(k)]));try{const response=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer,paymentMethod:fd.get('paymentMethod'),items:cart.map(l=>({productId:l.product.id,quantity:l.quantity}))})});const data=await response.json();if(!response.ok)throw new Error(data.error);setOrderId(data.order.id);setCart([])}catch(err){setError(err instanceof Error?err.message:'Checkout failed.')}finally{setSubmitting(false)}};
  const navigate=(next:View)=>{setView(next);setTimeout(()=>document.getElementById(next)?.scrollIntoView({behavior:'smooth'}),0)};
  return <main>
    <div className="announcement">Complimentary nationwide delivery on orders over ₱5,000</div>
    <nav className="nav"><button className="brand" onClick={()=>navigate('shop')}>KUMBINI<span>✦</span></button><div className="navlinks"><button onClick={()=>navigate('shop')}>Shop</button><button onClick={()=>navigate('story')}>Our story</button><button onClick={()=>navigate('makers')}>Makers</button></div><div className="navtools"><button aria-label="Search" onClick={()=>setSearching(!searching)}>⌕</button><button aria-label="Saved items" onClick={()=>{setQuery('');setCategory('All');setNotice(`${favorites.size} saved piece${favorites.size===1?'':'s'}`)}}>♡</button><a className="account" href="/signin-with-chatgpt?return_to=%2F">Account</a><button className="bag" onClick={()=>setCartOpen(true)}>Bag <span>{count}</span></button></div></nav>
    {searching&&<div className="searchbar"><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pieces, makers, materials…"/><button onClick={()=>{setQuery('');setSearching(false)}}>Close</button></div>}
    {notice&&<div className="toast" onAnimationEnd={()=>setNotice('')}>{notice}</div>}
    {view==='shop'&&<>
      <section className="hero" id="shop"><div className="hero-copy"><p className="eyebrow">Objects with a sense of place</p><h1>Beautiful things,<br/><em>made meaningfully.</em></h1><p className="lede">A considered collection of Filipino craft, everyday objects, and modern heirlooms—made by hands we know.</p><button className="primary" onClick={()=>document.getElementById('collection')?.scrollIntoView({behavior:'smooth'})}>Explore the collection <span>→</span></button><div className="proof"><strong>50+</strong><span>independent Filipino<br/>makers supported</span></div></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1610701596061-2ecf227e85b2?auto=format&fit=crop&w=1400&q=90" alt="Handmade ceramic vessels"/><div className="image-note"><span>01</span><p>Crafted slowly.<br/>Kept for years.</p></div></div></section>
      <section className="collection" id="collection"><div className="section-head"><div><p className="eyebrow">The collection</p><h2>Made to be lived with.</h2></div><p>{shown.length} pieces</p></div><div className="catalog-tools"><div className="chips">{categories.map(c=><button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></div><div className="product-grid">{shown.map(p=><article className="product" key={p.id}><button className="product-image" onClick={()=>setSelected(p)}><img src={p.image} alt={p.name}/><span className="quick">Quick view</span></button><button className={`heart ${favorites.has(p.id)?'saved':''}`} onClick={()=>toggleFavorite(p.id)} aria-label={`Save ${p.name}`}>{favorites.has(p.id)?'♥':'♡'}</button><p className="maker">{p.maker}</p><div className="product-title"><button onClick={()=>setSelected(p)}>{p.name}</button><span>{peso(p.price)}</span></div></article>)}</div>{shown.length===0&&<div className="empty"><h3>No pieces found</h3><p>Try a different search or category.</p></div>}</section>
      <section className="values"><div><p className="eyebrow">The Kumbini standard</p><h2>Good design should<br/><em>do good, too.</em></h2></div><div className="value-grid"><article><b>01</b><h3>Made by hand</h3><p>Every piece bears the quiet evidence of its maker—no two are exactly alike.</p></article><article><b>02</b><h3>Rooted locally</h3><p>We source directly from independent studios and family workshops across the Philippines.</p></article><article><b>03</b><h3>Chosen to last</h3><p>Natural materials, enduring forms, and objects designed for daily life.</p></article></div></section>
    </>}
    {view==='story'&&<section className="editorial" id="story"><div><p className="eyebrow">Our story</p><h1>A marketplace for things that carry a story.</h1><p>Kumbini began with a simple belief: the objects closest to us should feel personal, useful, and connected to place. We travel across the Philippines to meet craftspeople where they work, understand their materials, and bring their work to thoughtful homes.</p><p>Our name evokes gathering—people, stories, and beautiful things coming together. Every purchase supports an independent maker and helps a living craft move forward.</p><button className="primary" onClick={()=>navigate('shop')}>Shop the collection →</button></div><img src="https://images.unsplash.com/photo-1610701596061-2ecf227e85b2?auto=format&fit=crop&w=1200&q=90" alt="Maker at work"/></section>}
    {view==='makers'&&<section className="makers-page" id="makers"><p className="eyebrow">Meet the makers</p><h1>The hands behind the work.</h1><div className="maker-list">{Array.from(new Map(products.map(p=>[p.maker,p])).values()).map((p,i)=><article key={p.maker}><span>0{i+1}</span><div><h2>{p.maker}</h2><p>{p.story}</p><button onClick={()=>{setQuery(p.maker);navigate('shop')}}>View their work →</button></div></article>)}</div></section>}
    <section className="newsletter"><p className="eyebrow">Notes from the studio</p><h2>New pieces, maker stories,<br/>and thoughtful living.</h2><form onSubmit={e=>{e.preventDefault();setNotice('Welcome to the Kumbini journal')}}><input required type="email" aria-label="Email address" placeholder="Your email address"/><button>Join the journal →</button></form></section>
    <footer><button className="brand" onClick={()=>navigate('shop')}>KUMBINI<span>✦</span></button><p>Filipino objects for thoughtful homes.</p><div><button onClick={()=>navigate('shop')}>Shop</button><button onClick={()=>navigate('story')}>Our story</button><button onClick={()=>navigate('makers')}>Makers</button><a href="mailto:hello@kumbini.ph">Contact</a></div><small>© 2026 Kumbini. Made with care in the Philippines.</small></footer>
    {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="quick-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><img src={selected.image} alt={selected.name}/><div><p className="maker">{selected.maker}</p><h2>{selected.name}</h2><p className="modal-price">{peso(selected.price)}</p><p>{selected.description}</p><div className="story-note"><b>Maker story</b><span>{selected.story}</span></div><p className="stock">● {selected.stock} pieces available</p><button className="primary wide" onClick={()=>add(selected)}>Add to bag — {peso(selected.price)}</button></div></section></div>}
    <div className={`drawer-backdrop ${cartOpen?'open':''}`} onClick={()=>setCartOpen(false)}/><aside className={`cart-drawer ${cartOpen?'open':''}`} aria-hidden={!cartOpen}><div className="drawer-head"><div><p className="eyebrow">Your selection</p><h2>Shopping bag <span>{count}</span></h2></div><button onClick={()=>setCartOpen(false)}>×</button></div>{cart.length===0?<div className="cart-empty"><span>◇</span><h3>Your bag is waiting.</h3><p>Discover objects made to stay with you.</p><button className="primary" onClick={()=>setCartOpen(false)}>Explore pieces</button></div>:<><div className="cart-lines">{cart.map(l=><article key={l.product.id}><img src={l.product.image} alt=""/><div><p className="maker">{l.product.maker}</p><h3>{l.product.name}</h3><span>{peso(l.product.price)}</span><div className="quantity"><button onClick={()=>quantity(l.product.id,l.quantity-1)}>−</button><b>{l.quantity}</b><button onClick={()=>quantity(l.product.id,l.quantity+1)} disabled={l.quantity>=l.product.stock}>+</button></div></div><button className="remove" onClick={()=>quantity(l.product.id,0)}>Remove</button></article>)}</div><div className="cart-summary"><div><span>Subtotal</span><b>{peso(subtotal)}</b></div><p>{shipping===0?'You unlocked complimentary delivery.':'₱180 delivery · Free over ₱5,000'}</p><button className="primary wide" onClick={()=>{setCartOpen(false);setCheckout(true)}}>Secure checkout →</button></div></>}</aside>
    {checkout&&<div className="modal-backdrop"><section className="checkout-modal"><button className="close" onClick={()=>{setCheckout(false);setOrderId('')}}>×</button>{orderId?<div className="success"><span>✓</span><p className="eyebrow">Order confirmed</p><h2>Salamat!</h2><p>Your order <b>{orderId}</b> is now being prepared. A confirmation has been sent to your email.</p><button className="primary" onClick={()=>{setCheckout(false);setOrderId('')}}>Continue shopping</button></div>:<><div className="checkout-title"><p className="eyebrow">Secure checkout</p><h2>Delivery details</h2><span>{count} item{count===1?'':'s'} · {peso(subtotal+shipping)}</span></div><form onSubmit={submitOrder} className="checkout-form"><label>Full name<input name="name" required autoComplete="name"/></label><label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Phone<input name="phone" required autoComplete="tel"/></label><label className="full">Street address<input name="address" required autoComplete="street-address"/></label><label>City / Municipality<input name="city" required autoComplete="address-level2"/></label><label>Postal code<input name="postalCode" required autoComplete="postal-code"/></label><fieldset className="full"><legend>Payment method</legend><label className="pay"><input type="radio" name="paymentMethod" value="cod" defaultChecked/><span><b>Cash on delivery</b><small>Pay when your order arrives</small></span></label><label className="pay"><input type="radio" name="paymentMethod" value="bank"/><span><b>Bank transfer</b><small>Instructions sent after checkout</small></span></label></fieldset>{error&&<p className="form-error full">{error}</p>}<div className="checkout-total full"><div><span>Subtotal</span><b>{peso(subtotal)}</b></div><div><span>Delivery</span><b>{shipping?peso(shipping):'Complimentary'}</b></div><div className="grand"><span>Total</span><b>{peso(subtotal+shipping)}</b></div></div><button disabled={submitting} className="primary wide full">{submitting?'Placing your order…':`Place order · ${peso(subtotal+shipping)}`}</button></form></>}</section></div>}
  </main>
}
